import Service from './Service';

export default class OrganizationService extends Service {

    read = () => { 
        const chaine = "<center><h1>La FONDATION MAX CADET d’HAÏTI</h1> <b>\"Des soins dentaires au plus grand nombre\"</b></center>"+ 
        "<p>Née de la volonté des 10 enfants du Dr Max CADET, dentiste décédé le 28 juin 1992 et de son épouse Thérèse"
        +"DEJOUR-CADET, la FMC d’Haïti est entrée dans sa 30 ème année d’existence. Avec ses cliniques"
        +"dentaires (la fixe au Canapé-Vert et les mobiles se déplaçant dans le milieu rural et les périphéries des villes) elle fait"
        +"fonctionner la plus grande structure de soins dentaires et de prévention bucco-dentaire du pays.</P>"
        +"<p>Les 40 salariés dont 13 dentistes, 13 assistants-dentaires et 2 prothésistes assurent l'accueil en soins de près"
        +"de 150 patients/jours sur 9 fauteuils installés. Pour la prévention bucco-dentaire, la FMC mobilise des équipes"
        +"formées en intervention maxillo-faciale et en prévention reliée à un programme d’Éducation à la santé.</p>"
        +"<p>Ces performances sont rendues possibles grâce au trépied que forment : "
        +"<ul><li><b>la Fondation Max CADET en Haïti</b> dont le Comité de gestion et la Direction assurent le fonctionnement des"
        +"Cliniques / la fixe au Canapé-Vert Port-au-Prince et les mobiles là où les demandes de prévention et de"
        +"soins sont formulées et pour lesquels nous recevons un soutien financier de quelques bailleurs internationaux;</li>"
        +"<li><b>le Relais « France-Europe » de la Fondation Max CADET d’Haïti avec le siège à Toulouse France</b></li>"
        +"<li><b>et la « Max Cadet Dental Fund Inc.» avec le siège à New-York USA</b>"
        +"dont les administrateurs et donateurs pourvoient aux lourds investissements et permettent ainsi aux cliniques (la"
        +"fixe et les mobiles) de disposer, d’un outil de travail qualitativement et quantitativement bien doté.</li></ul></p>"
        +"<p>Pour <b>la formation permanente</b> la FMC s’est appuyée sur un solide et instructif partenariat international. Débuté en"
        +"1998 avec la délégation internationale, composée des dentistes français Francis MOYEN (Syé Trophy France/"
        +"inventeur de la RVG-Radio Visio- graphie buccale), Etienne PHILIPPE (Faculté dentaire de Toulouse) et du dentiste"
        +"américain Snead MOSES (Faculté dentaire de New-York). Cette 1ère collaboration s'est prolongée par une longue série"
        +"de missions de partage d’expériences et d’élévation des capacités scientifiques et techniques entre les praticiens de la"
        +"Clinique et des étudiants en découverte de pathologies complexes et des professeurs qui les encadraient. Elle s'est"
        +"consolidée grâce aux <b>conventions signées entre ies Facultés dentaires</b> de Genève Suisse, de Thust University"
        +"Boston, de la Medical University Massachusetts et de Mehary Médical College NashvilleTennesse USA et la <b>FMC</b>.</p>"
        +"<p>Après le <b>séisme de 2010</b> il a fallu <b>démolir notre ancien bâtiment</b> ébranlé et devenu inapte à l'accueil du public. Pour"
        +"l'installation des unités de soins sur le nouveau site du Canépé-Vert, <b>la Fondation de France</b> nous a prêté une oreille"
        +"attentive, s'est renseigné sur notre structure et ses activités et <b>nous a accordé une subvention pour la relance des"
        +"soins au Canapé-Vert</b>, pour une offre massive de soins dans les camps et pour la reconstruction. <b>Les société civiles"
        +"solidaires de France et des USA</b> ont apporté les ressources complémentaires pour redresser la structure de soins..</p> "
        +"<p>Notre FONDATION est tendue vers son avenir. Malgré les crises, séismes et tempêtes elle veut poursuivre sa mission."
        +"Et le Relais France-Europe lui fournit son soutien pour réussir, comme en 2020 :"
        +"<ul><li><b>la maîtrise de la consommation d’eau usuelle</b> à la clinique fixe par la mise en place d’un <b>système de"
        +"potabilisation offrant l’eau</b>, <u>pour les besoins</u> en soins et en boisson des 200 personnes qui fréquentent tous"
        +"les jours le site et <u>déminéralisée</u> en vue de la stérilisation de prés de 1000 instruments dentaires/jour.</li></ul></P> "
        +"<p>Il reste à obtenir pour la FMC devant faire fonctionner sa clinique fixe :"
        +"<ul> <li> <b>l’autonomie énergétique</b> par la construction d’un Générateur Photovoltaïque, grâce à l’accompagnement"
        +"technique d’Électriciens Sans Frontières France et le soutien financier de plusieurs bailleurs français.</li>"
        +"<li> <b>l’achèvement de l’aménagement du site</b>, par la création des bureaux administratifs (direction, secrétariat,"
        +"comptabilité), de la Salle du personnel dédiée aux réunions, aux poses-café et au repas partagés. En atteignant"
        +"ces objectifs nous amélioreront les conditions de travail et, bien sûr, les performances d’une équipe dévouée à"
        +"la cause des patients que nous accueillons nombreux, souvent en souffrance mais appréciant de pouvoir"
        +"bénéficier des soins de qualité à bas prix, en cette clinique.</li>"
        +"<li>et enfin <b>la reconnaissance de notre rôle social, de notre modèle économique, de notre mission d’utilité"
        +"publique et de notre place dans l’évolution de la pratique dentaire en Haïti</b>. Notre offre de soins dentaires,"
        +"de prévention bucco-dentaire et de formation permanente est respectueuse des patients sur le plan qualitatif et"
        +"appréciable vue de son évaluation quantitative. Nous tenons à ce que la contribution, même faible, des patients"
        +"et les financements solidaires des campagnes de prévention, couvrent les charges salariales et celles de"
        +"fonctionnement (eau, énergie, entretien du site). Nous recevons de l’étranger les moyens de l’investissement"
        +"(structure et équipements) pour offrir aux praticiens les moyens <b>d’intervenir dans six spécialités</b> - la"
        +"Dentisterie opératoire ; - la Chirurgie parodontale, ; - l’Endodontie ; - l’Orthodontie ; - la Prophylaxie et de"
        +"<b>disposer d’un laboratoire de prothèses</b>. Notre centre de soins qui accueille beaucoup d’étudiants en soins"
        +"dentaire, est le lieu où se met en pratique le concept fondamental du soin dentaire défini par le Dr Max Cadet :"
        +" <b>\"encourager les soins préventifs plutôt que faire subir des soins d’urgence\"</b>.</li></ul></p>" 
        +"<p><b>Notre souhait, bénéficier d’une trêve dans les crises et achever en 2022, notre programme de prévention buccodentaire destinée aux scolaires de la périphérie est de Port-au-Prince.</b></p>";

        return chaine;
    }
}